site_name: Stable diffusion for Architects [KR]

nav:
  - 1.시작(생성형 AI): "index.md"
  - 2.설치(stable diffusion): "install.md"
  - 2.디자인 옵션 탐색(Prompt): 
      - How to Use : "2.DesignOptions/1.howtouse.md"
      - Parameter : "2.DesignOptions/2.parameters.md"
      - Prompt  : "2.DesignOptions/3.prompt.md"
  - 3.재료 및 텍스쳐 선택 (LoRA): 
      - Texture : "3.texture/texture.md"
      - LoRA : "3.texture/LoRA.md"
  - 4.주변 환경 적용(Control-net) : 
      - Control_net : "4.Control_net/Control_net_models.md"
  - 5.개념 시각화 및 도면 작업:
      - Visualization : "5.Visualization/visualization.md"
  - 6.Generative 3D:
      - Gen 3d: "6.Gen 3D modeling/gen3d.md"

  - Documenting (TBR):
      - Instructions: "documenting/instructions.md"
      - Folder Structure: "documenting/folder_structure.md"
      - Guidelines: "documenting/guidelines.md"

theme:
  name: "material"
  logo: "img/logo.png"
  favicon: "favicon.ico"
  palette:
    primary: "green"  # Escaping hex code
    accent: "dark green"
extra_css:
  - css/custom.css
markdown_extensions:
  - codehilite
  - pymdownx.keys
  - pymdownx.highlight
  - pymdownx.emoji
