site_name: Stable diffusion for Architects [KR]

nav:
  - 1.시작(생성형 AI): "index.md"
  - 2.설치(stable diffusion): "a1_planning.md"
  - 2.디자인 옵션 탐색(Prompt): 
      - How to Use : "2.DesignOptions/1.howtouse.md"
      - Parameter : "2.DesignOptions/2.parameters.md"
      - Prompt  : "2.DesignOptions/3.prompt.md"
  - 3.재료 및 텍스쳐 선택 (LoRA): "a3_massing.md"
  - 4.주변 환경 적용 (Control-net) : "a4_forming.md"
  - 5.개념 시각화 및 도면 작업: "about.md"
  - 6.Generative 3D:
      - Scripts: "index/scripts.md"
      - Figures: "index/figures.md"
      - Presentations: "index/presentations.md"
      - Bibliography: "index/bibliography.md"
  - Documenting (TBR):
      - Instructions: "documenting/instructions.md"
      - Folder Structure: "documenting/folder_structure.md"
      - Guidelines: "documenting/guidelines.md"

theme:
  name: "material"
  logo: "img/logo.png"
  favicon: "favicon.ico"
  palette:
    primary: "green"  # Escaping hex code
    accent: "\"#4f7c55\""

markdown_extensions:
  - codehilite
  - pymdownx.keys
  - pymdownx.highlight
  - pymdownx.emoji
