site_name: Stable diffusion for Architects [KR]

nav:
  - 0.Home: "index.md"
  - 1.시작(생성형 AI): 
      - What is Gen AI? : "1.Intro/intro.md"
      - What is Stable diffusion? : "1.Intro/stablediff.md"
  - 2.설치(stable diffusion): 
      - Install : "2.install/install.md"
  - 3.디자인 옵션 탐색(Prompt): 
      - Webui 기본 인터페이스 : "3.DesignOptions/interface.md"
      - Parameter : "3.DesignOptions/howtouse.md"
      - Prompt  : "3.DesignOptions/3.prompt.md"
      - txt to image : "3.DesignOptions/txt to img.md"
      - image to image : "3.DesignOptions/img to img.md"
      - inpaint-outpaint : "3.DesignOptions/inpaintoutpaint.md"
  - 4.재료 및 텍스쳐 선택 (LoRA): 
      - Texture : "4.texture/texture.md"
      - LoRA : "4.texture/LoRA.md"
      - How to LoRA: "4.texture/HowtoLoRA.md"
  - 5.주변 환경 적용(Control-net) : 
      - Control_net : "5.Control_net/Control_net_basics.md"
      - Control_net_models : "5.Control_net/Control_net_models.md"
  - 6.개념 시각화 및 도면 작업:
      - Visualization : "6.Visualization/visualization.md"
  - 7.Generative 3D:
      - Gen 3d: "7.Gen 3D modeling/gen3d.md"

  - Documenting (TBR):
      - Instructions: "documenting/instructions.md"
      - Folder Structure: "documenting/folder_structure.md"
      - Guidelines: "documenting/guidelines.md"

theme:
  name: "material"
  logo: "img/logo.png"
  favicon: "favicon.ico"
  palette:
    primary: "green"  # Escaping hex code
    accent: "dark green"
extra_css:
  - css/custom.css
markdown_extensions:
  - codehilite
  - pymdownx.keys
  - pymdownx.highlight
  - pymdownx.emoji
