site_name: Stable diffusion for Architects [KR]

nav:
  - 0.Home: "index.md"
  - 1.시작(생성형 AI): 
      - 1-1 AI? : "1.Intro/intro.md"
      - 1-2 Stable diffusion? : "1.Intro/stablediff.md"
  - 2.설치(stable diffusion): 
      - 2-1 로컬 설치 방법 : "2.install/install.md"
  - 3.디자인 옵션 탐색: 
      - 3-1 기본 기능 : "3.DesignOptions/howtouse.md"
      - 3-2 txt to image : "3.DesignOptions/txt to img.md"
      - 3-3 img to image : "3.DesignOptions/img to img.md"  
      - 3-4 inpaint : "3.DesignOptions/inpaintoutpaint.md"   
      - 3-5 upscale : "3.DesignOptions/upscaler.md"
  - 4.프롬프트 엔지니어링: 
      - 4-1 Prompt : "3.DesignOptions/3.prompt.md"        
  - 5.LoRA 스타일 적용:       
      - 5-1 LoRA : "4.texture/LoRA.md"
      - 5-2 How to LoRA: "4.texture/HowtouseLoRA.md"    
      - 5-3 How to train LoRA : "4.texture/train LoRA.md"  
      - 5-3 조경 디자인: "4.texture/LoRA_K조경.md"
      - 5-4 평,입,단면 도면: "4.texture/LoRA_평입단.md"
      - 5-5 인테리어 디자인:  "4.texture/LoRA_int.md"
  - 6.주변 환경 적용(Control-net) : 
      - 6-1 Control_net : "5.Control_net/Control_net_basics.md"
      - 6-2 Control_net_models : "5.Control_net/Control_net_models.md"
      - 6-2-1 Control_net depthmap: "4.texture/texture.md"
      - 6-2-2 Control_net sketch:  "4.texture/texture.md"
  - 7.빛과 조명연구:
      - 7-1 interior lighting : "6.Visualization/visualization.md"
      - 7-2 exterior lighting : "4.texture/texture.md"
  - 8.Generative 3D:
      - 8-1 Gen 3d: "7.Gen 3D modeling/gen3d.md"

  - Documenting (TBR):
      - Instructions: "documenting/instructions.md"
      - Folder Structure: "documenting/folder_structure.md"
      - Guidelines: "documenting/guidelines.md"

theme:
  name: "material"
  logo: "img/logo.png"
  favicon: "favicon.ico"
  palette:
    primary: "green"  # Escaping hex code
    accent: "dark green"
extra_css:
  - css/custom.css
markdown_extensions:
  - codehilite
  - pymdownx.keys
  - pymdownx.highlight
  - pymdownx.emoji
